/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MenuComponent {
    'menuTitle': string;
  }
}

declare global {


  interface HTMLMenuComponentElement extends Components.MenuComponent, HTMLStencilElement {}
  var HTMLMenuComponentElement: {
    prototype: HTMLMenuComponentElement;
    new (): HTMLMenuComponentElement;
  };
  interface HTMLElementTagNameMap {
    'menu-component': HTMLMenuComponentElement;
  }
}

declare namespace LocalJSX {
  interface MenuComponent extends JSXBase.HTMLAttributes<HTMLMenuComponentElement> {
    'menuTitle'?: string;
  }

  interface IntrinsicElements {
    'menu-component': MenuComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


